# Site settings
title:  Marcin Henryk Bartkowiak # Title of your site
author: Marcin Henryk Bartkowiak # Title of your site
email:  mhbartkowiak+blog@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Marcin Henryk Bartkowiak's homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mhib.github.io" # the base hostname & protocol for your site

# social stuff
twitter_username:    mhbartkowiak
github_username:     mhib
linkedin_username:
google_plus_username:
facebook_username:
dribbble_username:

# Build settings
markdown:    kramdown
highlighter: pygments
timezone:    'Europe/Warsaw'
paginate:    5
