# Site settings
title:  Marcin Henryk Bartkowiak # Title of your site
author: Marcin Henryk Bartkowiak # Title of your site
email:  mhbartkowiak+blog@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Homepage
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://mhib.github.io" # the base hostname & protocol for your site

# social stuff
twitter_username:    mhbartkowiak
github_username:     mhib
linkedin_username:
google_plus_username:
facebook_username:
dribbble_username:

# Build settings
markdown:    kramdown
highlighter: pygments
timezone:    'Europe/Warsaw'
paginate:    5

# octopress
# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

gems: [jekyll-paginate]
